# Generated by Django 4.2 on 2024-07-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
    ]
